- docs/3.-Guides/CRM/1-CustomerRelationshipManagement.md
- docs/3.-Guides/CRM/Accounts.md
- openapi/platform/platform.yaml
Document basic create account group and create contact endpoints. Terms are based on @jmartens-va's [recommendations](https://vendasta.jira.com/wiki/spaces/~531910978/pages/716996992/RFC+Default+terms+Accounts+and+user+types) 
This is a minimal set of functionality to support the requirements [here](https://vendasta.jira.com/wiki/spaces/API/pages/717325047). List and update endpoints will come later.
For a more pleasant viewing experience, you can check out this branch then use the desktop app https://stoplight.io/studio/ to open the repo. Feel free to leave comments on this PR but keep in mind it is a public repo. 
@vendasta/external-apis @vendasta/psycho-billers 
EA-21
> Add accountLocations and accountContacts

- docs/Guides/Sell/FindSKU.md
- docs/Guides/Sell/Overview.md
- toc.json
Adding some guides to go with the new orders endpoints. 
@ncline-va would you mind filling in the Find a SKU page from the list of products without order forms that you have before this is merged.
Within the `Sell` folder (open to other names) I would like to see full page guides to activate the Online Toolkit and other O&O products for a brand new business location. I'm going to leave them out for now. 
We may want to break some of the other examples out into their own pages as well so that we can track pageviews to each of them. Thoughts?  
You may preview the guides [here](https://vendasta.stoplight.io/docs/openapi-specs/branches/preview-orders-guides/docs/Guides/Sell/Overview.md).
EA-200
@vendasta/external-apis @jredl-va @ncline-va @AllanWolinski
> Add orders guides

- docs/Authorization/2-legged-oauth/CreatingAServiceAccount.md
- docs/Authorization/2-legged-oauth/UsingAServiceAccount.md
Rewrite the guide for creating a 2-legged OAuth2 access token from the perspective of a partner. 
You may preview the page [here](https://docs.apigateway.co/docs/openapi-specs/branches/EA-232-access-token-guide/docs/Authorization/2-legged-oauth/UsingAServiceAccount.md)
EA-232 @vendasta/external-apis @vendasta/teamy-mcteamface
> Clarify the access token guides

- openapi/platform/platform.yaml
Change the display name of the security schema from `OAuth` to `OAuth2` for clarity. Potentially we should rename it `OAuth2 - Demo` and duplicate it for prod. 
> Rename security schema

- toc.json
I accidentally put the Advertising Intelligence Guide under the Platform API divider instead of the guides section.
This PR moves it to the right place
@vendasta/adlads 
@richard-rance
> AD-666 Move Guide Location

- openapi/adintel/adintel.yaml
The options requests weren't appearing in the correct spot in the docs, so I decided to remove the accountStats tags so that the options tags would apply
> AD-666 Remove extra tags for options requests

- toc.json
Adds the social folder to the `products` branch of our documentation.
@richard-rance @Short-Hop @ndougherty-va @wfehr-va @DewaldoDev
[SOC-2047]: https://vendasta.jira.com/browse/SOC-2047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SOC-2047] Add Social pages to TOC.

- openapi/advertising/advertising.yaml
Sets all the advertising endpoints lifecycles to trusted tester.
@vendasta/adlads
> AD-670 Set Advertising endpoints to Trusted Tester

- toc.json
ToC link for the review request guide got overwritten on merge. 
[CUS-1859]
[CUS-1859]: https://vendasta.jira.com/browse/CUS-1859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(customers): reference correct guide path for CV

- docs/Guides/Social/socialProfiles.md
[SOC-2408] fix minor mistake in Social Profiles guide.
BusinessId was not defined correctly, so the guide tutorial didn't work.
[SOC-2408]: https://vendasta.jira.com/browse/SOC-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SOC-2408] fix minor mistake in Social Profiles guide.

- docs/Guides/CustomerVoice/SendReviewRequest.md
- openapi/customervoice/customervoice.yaml
Testing the "create customer" endpoint with the "send review request" endpoint has confirmed a substantial syncing delay between creating a customer record in Customer List and having that contact information synced to Customer Voice. 
The current solution is to suggest implementing a 30 second wait between creating a new customer and sending a review request to them. When implementing this at scale, we would most likely want to handle this logic with something like Zapier or work towards a more stable v2 for review request sending.
[CUS-1893]
[CUS-1893]: https://vendasta.jira.com/browse/CUS-1893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(reviewRequest): update sending guide to 30s wait

- openapi/platform/platform.yaml
Documentation page is not being able to display operations with long names, and some of them end up with the same prefix
Re-organize and chose shorter names
I also add a small fix in a link, that I thought that I did in the last PR
@vendasta/np-easy 
[AG-1371](https://vendasta.jira.com/browse/AG-1371)
> Custom Fields: Long names are not being displayed (AG-1371)

- docs/Guides/Listings/Listing.md
- openapi/listings/listings.yaml
Changed business entity to business location.
Changed paths:
`businessEntityListings` to `listingSyncListings`
`businessEntityListingScores` to `listingScore`
@jredl-va
> LB-2347: Update terminology for listings API

- openapi/platform/platform.yaml
We have added dropdown and currency to our services, but `api-gateway` doesn't use them.
Add support to dropdown and currency.
For currency, the `currencyCode` is part of the schema and not of the value. Also it's worth to note that currency is a `integer` because the decimal part is handled accordingly of the currency code.
I also refactored how the validation of types is processed
@vendasta/np-easy 
[AG-1543](https://vendasta.jira.com/browse/AG-1543)
[AG-1544](https://vendasta.jira.com/browse/AG-1544)
> Custom Fields: Add support to Dropdown and Currency types (AG-1543)(AG-1544)

- openapi/platform/platform.yaml
It turns out that you can't reference things outside the file. I think this is cause the file structure changes when you use `inv vendor:oas`. This adds the page refs into the platform.yaml so I can use it there.
auto-2047
@vendasta/autobots @richard-rance
> feat: add page limit and cursor to platform.yaml

- openapi/business/business.yaml
- openapi/platform/platform.yaml
@vendasta/data-busters 
@DewaldoDev  (if you have time to review) 
@hchow-va (if you have time to review)
Expose apis for list, get and update. This extends the existing create customer api that exists. Note, that I've removed some of the "business app" verbiage as we want to ensure its understood that these apis can be used by marketplace / smb products.
> feat: Expose apis for list get and update customer operations

- openapi/platform/platform.yaml
Refining proposal builder documentation that was recently added.
Overview:
- `lineItem.id` -> `lineItem.sku`
- removed `Trusted Tester` status on proposal models (must've been a copy/paste issue)
- added various descriptions and examples 
**TODO**:
@vendasta/typesafety-squad 
> Audit Proposal Builder Docs

- openapi/platform/platform.yaml
Snapshot doesn't exist as a model in `api-gateway`
Remove Snapshot relationship from Proposal
[Slack Discussion](https://vendasta.slack.com/archives/C01JG2JKJJJ/p1661796658891809?thread_ts=1661794629.766329&cid=C01JG2JKJJJ)
**TODO**:
@vendasta/typesafety-squad
> Remove Snapshot from Proposal

- openapi/platform/platform.yaml
The first element type is a page element, so the default type needs to be pageTemplate. Otherwise the example will attempt to create a widget template with a page as the top-level element.
**TODO**:
> Fix create proposalTemplate example

- openapi/platform/platform.yaml
Possible fix for the issue shown in video below:
https://user-images.githubusercontent.com/82058487/193891003-60afdafd-6bab-45a5-8b33-ffe025510110.mov
**TODO**:
> Fix operation ids for proposalTemplate requests

- openapi/social/social.yaml
@vendasta/phoenix 
Since api-gateway repo sync `social.yaml` file from here, it is better to update the file with OAuth2Demo & OAuth2Prod. So that `inv vendor:oas` sync, will not make the unit test to fail.
**TODO**:
> Update social yaml with OAuthDemo,OAuthProd

- docs/SSO/IDP-User-Sync.md
- docs/SSO/Identity-Provider-SSO.md
- docs/SSO/Overview.md
- toc.json
This new guide is to help partners that have their own database of users sync them with Vendasta. The reference partner is CoStar (FREN) as they are trying to replace just in time user creation with explicitly creating user ahead of time.
> Add a guide for syncing users with the platform from a partner's database

- openapi/reputation/reputation.yaml
All of our listing ids are of the format `LIS-804D842ABC0743AC8E345126911477DC`. That is not an integer, so change the type to a string.
REP-476
@vendasta/external-apis @vendasta/redmagic 
**TODO**:
> fix(business location reviews): change type of filter[businessListing.id] to string

- openapi/reputation/reputation.yaml
Implementation for the suggest review response API was done in https://github.com/vendasta/api-gateway/pull/329. The docs should be updated from proposed to trusted tester
Do that.
@vendasta/external-apis @vendasta/redmagic 
[REP-475]
[REP-475]: https://vendasta.jira.com/browse/REP-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(reputation): change suggest review response to trusted tester

- openapi/platform/platform.yaml
This is Regarding The doc changes for Cancel Subscription Assignment
**TODO**:
> PHNX-24 doc changes for cancel product api

- openapi/social/social.yaml
Add external id as one of the params. External id will be used later to retrieve the posts. 
**TODO**:
> SM-688: Add external id as params

- .spectral.mjs
A HackerOne report was created detailing apparent API tokens disclosed in plaintext.
The token doesn't appear to be needed for accessing the spectral.js file, nor does it seem to grant access to any sensitive files or API endpoints (it may have been needed at one point when this file was private?). To avoid future reports, I am removing it. If we do find out where this token came from, we can probably delete it or rotate it if required.
@vendasta/external-apis @richard-rance
> chore(spectral): remove unneeded token

- openapi/listings/listings.yaml
This line about the 200 pagination limit no longer applies, as the default min and max of 10 and 100 will be applied to this endpoint's pagination
**TODO**:
> LIS-1048 Update citation page limit docs

- openapi/reputation/reputation.yaml
Update documentation for the changes in https://github.com/vendasta/api-gateway/pull/422 to add modifiedAt and editedAt into BusinessLocationReview.
@vendasta/redmagic 
@vendasta/data-busters 
**TODO**:
> chore: update doc about adding modified time and edited time on BusinessLocationReview

- docs/Guides/Sell/FindSKU.md
SOD shared that it had a duplicated "EDITION" word that needed to be fixed on the documentation
> Remove duplicated "Edition" word

- docs/Guides/Sell/FindSKU.md
- docs/Overview/Changelog.md
We now have Reputation Management Premium, but it was not added to the docs yet.
Add it where the editions for Reputation Management are listed in the `findSKU` page.
I remember having to pull into updates to `api-gateway`, but I'm guessing that's not necessary this time since it's purely a text change and not something to do with a particular endpoint?
**TODO**:
[REP-549]
[REP-549]: https://vendasta.jira.com/browse/REP-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(find sku): add RM premium edition

- openapi/platform/platform.yaml
Update BusinessLocations and SalesAccounts models to have the new fields `tollFreeNumber`, `callTrackingNumbers`, `commonNames`. 
The wording of the descriptions of the fields are subject to change still
@vendasta/pioneers 
**TODO**:
> feat: Add tollFreeNumber, callTrackingNumbers, commonNames to businessLocations and salesAccounts

- openapi/platform/platform.yaml
Marks the Hours object used by the platform APIs as deprecated, referencing the Local SEO Listing Profile APIs as the new place to set hours
**TODO**:
> LIS-1231 Deprecate old platform hours model

- openapi/listings/listings.yaml
Updates the docs to indicate that all listing profile fields can now be set using this API
**TODO**:
> LIS-1330 Update docs for Listing Profile Update endpoint

- openapi/social/social.yaml
Updated some changes in POST message endpoint documentation
Reference : [SM-1134](https://vendasta.jira.com/browse/SM-1134)
Changed sendAt to scheduledAt
Made these fields unexposed (id, media->type, postedAt, relationships->socialProfiles->data->type , relationships->businessLocation->data->type)
**TODO**:
@vendasta/tots 
[SM-1134]: https://vendasta.jira.com/browse/SM-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SM-1134] Schedule social post doc update

- openapi/platform/platform.yaml
Since we are now using listing profile endpoints for all of our platform account apis, we no longer need to deprecate these hours.  Also updates the special hours docs to match how they are actually labelled and handled by the code.
**TODO**:
> LIS-1507 Set Hours on Platform APIs as no longer deprecated

- openapi/listings/listings.yaml
Update the status of implemented endpoints from `Proposed` to `Trusted Tester`.  Remove the `listingProfile.id` parameter in our `List Listing Sync Listings` endpoint in favor of the `businessProfile.id` one, since it is the parameter we use for other endpoints as well.
**TODO**:
> LIS-1586 Update Listings Docs

- openapi/reputation/reputation.yaml
[MRNA-1164](https://vendasta.jira.com/browse/MRNA-1164): Documentation Update: Pagination Limit of 10,000 Records for List Business Location Reviews
**Changes**: Updated the description of cursor for List Business Location Reviews
@vendasta/external-apis 
**TODO**:
[MRNA-1164]: https://vendasta.jira.com/browse/MRNA-1164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MRNA-1164] - Pagination Limit of 10,000 Records for List Business Location Reviews

- openapi/crm/crm.json
- openapi/platform/platform.yaml
In discussion with business folks related to hearst we have a problem. They have started to migrate to our new apis and the apis they are using in their sdk are not supported in our new apis. 
Attempting to expose the undo cancell api by just adding another new keyword to the api. Implemented here: https://github.com/vendasta/api-gateway/pull/567/files
> Add undo cancellation api endpoint

- openapi/platform/platform.yaml
Quick change to allow users to test api calls from the documentation by only changing the partner id. 
The default example based off the businessLocation object contained data that caused errors
- updatedDate
- same closing as opening time for hours
> allow testing of location creation with usable example

- docs/Overview/Changelog.md
- openapi/business/business.yaml
- openapi/crm/crm.json
People are often getting confused about the legacy Customer LIst endpoints and the new CRM endpoints. The API was deprecated last year, but I missed merging this earlier.
> Marketing customer list apis as deprecated

- toc.json
Adding paths for gRPC- gateway docs 
Can we expose Internal API here ? or shall we just have in repo and not show in UI 
**TODO**:
> update toc json

- toc.json
The documentation for the GRPC services cannot be rendered under a single file as the file is large and Stoplight seams to have limitation.  To overcome this limitation, for each service a separate file is to be generated.  An item entry is required in the toc.json for the each of the file.  This PR create a section and items based on the files generated can be added to this section. 
**TODO**:
@vendasta/marina @vendasta/phoenix
> create section for external grpc documentation in the developer center
