vendasta/api-gateway-docs

openapi/platform/platform.yaml
Updating documentation to reflect changes based on feedback on https://github.com/vendasta/api-gateway/pull/10
@vendasta/lucky-charms @richard-rance @vendasta/psycho-billers
=> Updating PayableInvoices documentation

docs/1.-Overview/Changelog.md, openapi/platform/platform.yaml
Document the `PATCH /platform/businessLocations` endpoint for updating business locations
EA-92
=> Add Update business locations

openapi/platform/platform.yaml
Propose a endpoint to list business categories
=> Business categories

openapi/platform/platform.yaml
OSA Spec for list orders and business locations. 
@richard-rance
=> List apis locations orders

docs/3.-Guides/CRM/Accounts.md, openapi/platform/platform.yaml
While testing the list orders endpoint its not really usable without order status. 
@vendasta/systems
=> Add order status to the order model

docs/Overview/Changelog.md, openapi/platform/platform.yaml
Add support for manually triggering order based automations
@vendasta/autobots @vendasta/external-apis 
AUTO-1801
=> Auto 1801 add support for order automations

openapi/platform/platform.yaml
Add a new resource for sales accounts
@dhopkins-va @vendasta/external-apis
=> Add a sales account model and endpoints

docs/Guides/Advertising/accountStats.md, openapi/advertising/advertising.yaml
Updates the account stats docs to require one business location ID instead of allowing multiple.
@vendasta/adlads
=> AD-666 Update accountStats docs

docs/Guides/Advertising/connectedAccount.md, openapi/advertising/advertising.yaml
for accepting a single business location ID in the request
@vendasta/adlads
=> [AD-640] Update API description

openapi/social/social.yaml
A few needed changes to sync up this repo with what we're doing in https://github.com/vendasta/api-gateway/pull/79.
[SOC-2407]: https://vendasta.jira.com/browse/SOC-2407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SOC-2407] Updates to sync up with Social Profile API.

openapi/listings/listings.yaml
Filled out all the enum descriptions for the listings endpoint.
@vendasta/external-apis @jredl-va @Short-Hop @mzhao-va @wfehr-va @DewaldoDev
=> LB-2235: Add enum descriptions

docs/Guides/Advertising/connectedAccount.md, openapi/advertising/advertising.yaml
@vendasta/adlads @richard-rance
=> [AD-640] Change created & updated fields to createdAt & updatedAt

openapi/customervoice/customervoice.yaml
Update the `reviewrequest` docs with the proper`application/vnd.api+json` Content-Type.
[CUS-1837]
[CUS-1837]: https://vendasta.jira.com/browse/CUS-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(review-request): use correct Content-Type header

docs/Guides/Customer Voice/SendReviewRequest.md, openapi/customervoice/customervoice.yaml
Change the Customer Voice APIs from `products/reviewrequest/reviewRequests` to `products/reviews/reviewRequests`
@vendasta/cv-team @richard-rance 
[CUS-1837]
[CUS-1837]: https://vendasta.jira.com/browse/CUS-1837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(review-request): rename product path to "reviews" to avoid stutter

docs/Guides/Create-Business-Users.md, openapi/platform/platform.yaml
[EA-278]
---
@vendasta/teamy-mcteamface @vendasta/external-apis 
[EA-278]: https://vendasta.jira.com/browse/EA-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> document updating user businessLocations

docs/Guides/Advertising/campaignStats.md, openapi/advertising/advertising.yaml
Adds docs and guides for campaign stats get endpoints
@vendasta/adlads
=> AD-683 CampaignStats guide and docs

openapi/listings/listings.yaml
=> Lb 2235 touch ups

openapi/listings/listings.yaml
Adds the account group ID to the endpoint path.
@vendasta/external-apis @jredl-va @Short-Hop @mzhao-va @wfehr-va @DewaldoDev
=> LB-2235: Add listing score part deux, don't critically fail to create sane docs

openapi/listings/listings.yaml
Pluralize the endpoint name.
@vendasta/external-apis @jredl-va @Short-Hop @mzhao-va @wfehr-va @DewaldoDev
=> LB-2236: Pluralize listing score

docs/Guides/Advertising/accountStats.md, docs/Guides/Advertising/campaignInfo.md, docs/Guides/Advertising/campaignStats.md, docs/Guides/Advertising/connectedAccount.md, docs/Overview/Changelog.md, openapi/advertising/advertising.yaml, toc.json
Takes all the Ad Intel files from the products branch in preparation to merge them to master
@vendasta/adlads 
@richard-rance
=> AD-675 Release AdIntel docs

openapi/social/social.yaml
This PR cleans up the endpoint documentation for GET Social Profiles so that it's in a state where we can release it to Trusted Tester once the pagination has been finished.
Main changes:
- Remove all Phase 2 filters for now (they are fully documented in the Vision Document, we can add them later).
- Add query parameters around pagination.
[FPA-14]: https://vendasta.jira.com/browse/FPA-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FPA-14] Update and finalize Social Profile documentation for endpoint.

docs/Guides/Social/socialProfiles.md, docs/Overview/Changelog.md, openapi/social/social.yaml, toc.json
This PR takes what we have for the Social Profile endpoint and model on the `products` branch and brings it to master. I've also polished it up and gone through all of the Pre-Release checks: https://vendasta.jira.com/wiki/spaces/API/pages/1651769533/Pre+Release+Checks
[SOC-2408]: https://vendasta.jira.com/browse/SOC-2408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SOC-2408] Bring forward the Social Profile docs to the public site.

docs/Guides/Automate/TriggerAutomation.md
Added an intro sentence and a link to the support articles for Automations.
@sean-schroeder @richard-rance
=> Added additional information about Automations

docs/Guides/Advertising/accountStats.md, docs/Guides/Advertising/campaignInfo.md, docs/Guides/Advertising/campaignStats.md, docs/Guides/Advertising/connectedAccount.md, docs/Guides/CustomerVoice/SendReviewRequest.md, docs/Guides/Social/socialProfiles.md
Added links to resource center articles for the O&O products on their relevant pages.
@richard-rance @sean-schroeder
=> Added links to support articles for O&O products

docs/Overview/Changelog.md, openapi/listings/listings.yaml, toc.json
Added the new API operations as well as updated the change log and table of contents. The operations are being added as proposed operations for now.
@richard-rance
=> LB-2347: Add listingSyncListings and listingScore to master

docs/Overview/Changelog.md, openapi/platform/platform.yaml
Adding the documentation for Orders Custom Fields endpoints.
[AG-1455]
@vendasta/np-easy 
[AG-1455]: https://vendasta.jira.com/browse/AG-1455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AG-1455]Orders Custom Fields Endpoints

openapi/platform/platform.yaml
Add support to products custom fields
@vendasta/np-easy 
[AG-1456](https://vendasta.jira.com/browse/AG-1456)
=> Custom Fields: Products Custom Fields (AG-1456)

openapi/platform/platform.yaml
Some examples were missing the attribute `data`. This PR addresses that.
@vendasta/np-easy
=> [fix] fix doc example

docs/SSO/Identity-Provider-(IDP)-SSO.md
Created a new page to add the documentation that lives in Partner Center to the public documentation pages. Definitely needs more information but this is a quick way to remove some confusion from partners looking at our documentation.
@richard-rance
=> Added docs/SSO/Identity-Provider-(IDP)-SSO.md

openapi/platform/platform.yaml
Add Hours of Operation for Telkom
=> Add hours of operations to sales accounts and business locations

openapi/platform/platform.yaml
I didn't realize that this is actually done in here then copied over haha
auto-2047
@vendasta/autobots @richard-rance
=> feat: add docs for automations get

docs/Overview/Changelog.md, openapi/platform/platform.yaml
- Announce the new API operation to the world so that partners can start using it.
- Correct the pluralization in the example
- Adjust the tags to fix the navigation menu
@coreyhickson can you please merge this into your future changes and add to the api-gateway µs. (`inv vendor:oas`)
@vendasta/autobots
=> Update Automations docs

docs/Overview/Changelog.md, openapi/platform/platform.yaml
This is a first cut at gathering the Assigned Subscriptions for a Location.
See Resource Vision: https://vendasta.jira.com/wiki/spaces/API/pages/edit-v2/1710916707
=> Subscription Assignment

openapi/advertising/advertising.yaml, openapi/platform/platform.yaml
Reverts vendasta/api-gateway-docs#99
=> Revert "Options cleanup"

docs/Overview/Changelog.md, openapi/platform/platform.yaml
[Proposals External APIs](https://vendasta.jira.com/wiki/spaces/API/pages/1763411335/Proposals)
Authors: @dthiessen-va @r-LaForge @Wynston 
[x] Review the [pre release checklist](https://vendasta.jira.com/wiki/spaces/API/pages/1651769533/Pre+Release+Checks)
=> Proposals API

openapi/platform/platform.yaml
To address this comment: https://github.com/vendasta/api-gateway/pull/173#discussion_r973340437
**TODO**:
=> add searchTerm query param to list proposal/proposalTempalte

openapi/platform/platform.yaml
**TODO**:
@byates-va @richard-rance
=> Add salesPerson relation to order

openapi/platform/platform.yaml
@vendasta/marina 
[MRN-284](https://vendasta.jira.com/browse/MRN-284)
**TODO**:
[ ] Review the [pre release checklist](https://vendasta.jira.com/wiki/spaces/API/pages/1651769533/Pre+Release+Checks)
=> Add tags to the orders API

openapi/scim/scim.yaml
[MRN-387](https://vendasta.jira.com/browse/MRN-387)
@vendasta/marina 
**TODO**:
[MRN-387]: https://vendasta.jira.com/browse/MRN-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated scopes in SCIM Get User API

openapi/scim/scim.yaml
=> Edited example formats for scim attributes

openapi/advertising/advertising.yaml, openapi/business/business.yaml, openapi/customervoice/customervoice.yaml, openapi/listings/listings.yaml, openapi/platform/platform.yaml, openapi/reputation/reputation.yaml, openapi/scim/scim.yaml, openapi/social/social.yaml
@vendasta/phoenix 
[PHNX-5](https://vendasta.jira.com/browse/PHNX-5) - Prefill access token on documentation site
Added security schemes OAuthDemo & OAuthProd to all endpoints.
**TODO**:
[PHNX-5]: https://vendasta.jira.com/browse/PHNX-5?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Phnx-5] Adding Demo/Prod security schemes

openapi/platform/platform.yaml
=> [PHNX-1] spotlight changes for account update date

openapi/platform/platform.yaml
AUT-1879
I added these scopes to the list endpoints not the get endpoints
@vendasta/autobots
=> add read scopes to the find one implementation

openapi/platform/platform.yaml
=> Add user read as a scope on the get user api

docs/Guides/Scim/Limitation of SCIM in Vendasta.md, docs/Guides/Scim/SCIM-Groups-and-their-assignment-to-users.md, toc.json
This PR documented the limitation or special behaviour of our SCIM APIs.
**TODO**:
=> MRNA-494: SCIM documentation update on limitation of SCIM

docs/SSO/Implementing-Oauth2-IDP.md
=> [PHNX-45] Write partner guide to implementing OAuth2 IDP (modification)

openapi/platform/platform.yaml
=> [PHNX-88] Filter salesAccounts by customer identifier

openapi/platform/platform.yaml
Updated gateway docs for send welcome email api
**TODO**:
=> Modified openapi/platform/platform.yaml

openapi/reputation/reputation.yaml
@ksheasby-va @ahenry-va @jonjazzy
=> Define new API for review response suggestions

openapi/listings/listings.yaml
=>  fix update listing profile endpoint

openapi/listings/listings.yaml
=> LIS-183 fix endDate property indocs

openapi/listings/listings.yaml
=> Update special hours doc

docs/SSO/Identity-Provider-SSO.md, docs/SSO/Implementing-Oauth2-IDP.md, docs/SSO/Single-Logout.md
Document the way that partners with custom OAuth2 IDPs can setup logout in response to [support question](https://vendasta.slack.com/archives/C01KLEB271Q/p1689369013456469)
@vendasta/teamy-mcteamface
=> Add single logout docs

openapi/social/social.yaml
List the curated content
SM-688: https://vendasta.jira.com/browse/SM-688
**TODO**:
=> SM-688: List curated content

openapi/social/social.yaml
List curated content
SM-688: https://vendasta.jira.com/browse/SM-688
**TODO**:
=> Sm 688 update social

openapi/platform/platform.yaml
Reverts vendasta/api-gateway-docs#165
=> Revert "added reason and comments for cancellation of products"

openapi/platform/platform.yaml
=> Previous reverted changes are now pushed

toc.json
[MRNA-712](https://vendasta.jira.com/browse/MRNA-712) : Move SCIM documentation to SCIM section (moved SCIM from coming soon to SCIM section)
**TODO**:
[MRNA-712]: https://vendasta.jira.com/browse/MRNA-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MRNA-712] - Move SCIM documentation to SCIM section

openapi/social/social.yaml
@vendasta/tots 
Update the master branch to be up-to-date with products with `messages` and `GET` API recently added. 
This PR would reduce some differences between the two branches.
The `post` call to create messages would still be under `products` branch, since we currently don't have any plans to open it for wider audiences.
**TODO**:
=> Sm-716 update master to make social.yaml same as product branch

docs/Guides/Sell/FindSKU.md, docs/Guides/Sell/OnlineToolkit.md, docs/Guides/Sell/Overview.md, docs/Overview/Changelog.md, docs/Overview/ProductOverview.md, toc.json
Renamed Listing Builder to Local SEO and added the necessary editions and addon skus
@vendasta/insync
**TODO**:
=> LIS-900 Rename Listing Builder and add editions/addon skus

openapi/listings/listings.yaml, openapi/platform/platform.yaml
=> Fix missed strings

openapi/social/social.yaml
We have done a demo with a prospect client, would like to release it as a General Available API.
@vendasta/tots 
**TODO**:
=> SM-716: Moving flag to GA

openapi/social/social.yaml
@vendasta/tots 
Moving `/messages` to trusted testers as well.
**TODO**:
=> SM-716: Moving flag to TT first

openapi/platform/platform.yaml
@vendasta/external-apis 
**TODO**:
=> added isNewCategory query param in business location and sales account

openapi/platform/platform.yaml
https://vendasta.jira.com/browse/PHNX-240
**TODO**:
=> doc changes for Cancel Products over API with the Deactivate immediately flag

openapi/platform/platform.yaml
=> renamed query param

openapi/platform/platform.yaml
=> PHNX-221-Modify List Business Categories API 

openapi/platform/platform.yaml
=> phnx-221-Modify-List-Business-Categories-API 

openapi/listings/listings.yaml
=> LIS-1006 Add get citation data endpoint

openapi/platform/platform.yaml
=> Filter by fields of businessLocations and salesAccounts

openapi/platform/platform.yaml
=> fixed bug by extending limit of characters of names of users

openapi/crm/crm.json
[MRNA-788](https://vendasta.jira.com/browse/MRNA-788) 
@vendasta/external-apis 
**Changes**: Upsert CRM record endpoint is added to crm.json file.
**TODO**:
[MRNA-788]: https://vendasta.jira.com/browse/MRNA-788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MRNA-788] Document Upsert API

openapi/platform/platform.yaml
Made a typo with one of the field names. It is `trackingNumbers` rather than `callTrackingNumbers`
@vendasta/pioneers 
**TODO**:
=> Fix Field Name Tracking Numbers

openapi/platform/platform.yaml
@vendasta/pioneers 
@vendasta/external-apis 
Documentation for new fields added in https://github.com/vendasta/api-gateway/pull/460.
**TODO**:
=> Update docs with new fields on SalesAccounts

openapi/platform/platform.yaml
This PR updates the API docs for Automation Get API which enables the api to return custom parameters setup in automation UI.
- [Zapier Automation RFC](https://vendasta.jira.com/wiki/spaces/RD/pages/2250179140/RFC+-+Zapier+Action+to+trigger+Vendasta+Automation#Get-Automation)
- [MRNA-913](https://vendasta.jira.com/browse/MRNA-913)
**TODO**:
[MRNA-913]: https://vendasta.jira.com/browse/MRNA-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MRNA-922] Automation API docs updated to return customParameters

openapi/platform/platform.yaml
=> support multi ids in sales account and business location

openapi/platform/platform.yaml
Reverts vendasta/api-gateway-docs#198
adding some test cases
=> Revert "support multi ids in sales account and business location" for backend changes

openapi/platform/platform.yaml
- Modify List API specifications
**TODO**:
=> Modify list automation API

openapi/platform/platform.yaml
=> support multi ids

openapi/platform/platform.yaml
https://vendasta.jira.com/jira/software/c/projects/PHNX/boards/468?selectedIssue=PHNX-538
We are doing for multi support of ids in business location and sales account .Example should be like that so user will know how to put id in filter[id] param.
**TODO**:
=> example for filter id in business account and sales account

openapi/listings/listings.yaml
Add ICO field to listing profile docs so it can be set for czech businesses via this API
**TODO**:
=> LIS-1392 Add ICO to listing profile API docs

docs/Authorization/2-legged-oauth/UsingAServiceAccount.md
I requested a token in Python. I figured it would make a good example after some cleanup. The code I provided works.
**Note, however, that I updated the doc file by hand in vscode.** Seems legit? 😬 
**TODO**:
=> Add Python example

openapi/listings/listings.yaml, openapi/platform/platform.yaml
Update description for business categories under businessLocation model
@vendasta/insync
**TODO**:
=> LIS-1610 Update description for business categories under businessLocation model

docs/SSO/Identity-Provider-SSO.md
Updated the Overview for IDP SSO. 
- Fixed conflation of OAuth2.0 & OIDC
- Ensured all associated prerequisites and related documentation was highlighted
- Removed invalid statement about PKCE being required
I'll likely follow up with some adjustments to the PC SSO page.
=> Ncline sso updates

openapi/crm/crm.json
This List method is somewhat different from other methods, as it is using a POST instead of a GET to 
retrieve the information, mainly because we can use a number of filters that would easily have a size that
would be greater than the allowed for query parameters.
=> CRMAAS-2034 - Endpoint for Listing CRM objects

openapi/crm/crm.json
Deleted more than was supposed to in my last PR, putting the deleted parts back
**TODO**:
=> CRMAAS-2034 - Deleted more than needed

openapi/crm/crm.json
=> Crmaas 2041

openapi/crm/crm.json, openapi/crm/operators_by_type.txt
**TODO**:
Add more detailed information on operators on the request for the List CRm Records
=> CRMAAS-2198 - Updating the documentation for CRM

openapi/crm/crm.json
=> CRMAAS-2222 - Adding subtype for custom objects.
